---
driver:
  name: docker
  use_sudo: false

driver_config:
#  require_chef_omnibus: "12.7.2"
  dns:
    - "8.8.8.8"

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: 

platforms:
  - name: centos
    driver_config:
      platform: centos
      image: my-centos:6.8
      username: "root"
      privileged: true

suites:
  - name: default
    run_list:
      - recipe[ddb::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
