---
driver:
  name: docker
  use_sudo: false
#  binary: docker.exe # <--because you are on windows
#  socket: "tcp://127.0.0.1:2375" # windows

driver_config:
#  require_chef_omnibus: "12.7.2"
  dns:
    - "8.8.8.8"
    - "10.6.0.6"
    - "10.6.0.16"

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos
    driver_config:
      platform: centos
      image: siah/centos:6.8
      username: "root"
      privileged: true

suites:
  - name: default
    driver:
      links: "dynamodb:dynamodb"
    run_list:
      - recipe[ddb::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
