FROM centos:6.8

            ENV container docker
            RUN yum clean all
            RUN yum install -y sudo openssh-server openssh-clients which curl
            RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
            RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ''

          RUN if ! getent passwd root; then                 useradd -d /root -m -s /bin/bash root;               fi
          RUN echo root:kitchen | chpasswd
          RUN echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          RUN echo "Defaults !requiretty" >> /etc/sudoers
          RUN mkdir -p /root/.ssh
          RUN chown -R root /root/.ssh
          RUN chmod 0700 /root/.ssh
          RUN touch /root/.ssh/authorized_keys
          RUN chown root /root/.ssh/authorized_keys
          RUN chmod 0600 /root/.ssh/authorized_keys


RUN echo ssh-rsa\ AAAAB3NzaC1yc2EAAAADAQABAAABAQDQN8OaohGmNd7m3eA5Qcg7J6is0sWE5tTT46Yk2b4IUV4XS68Jf7qKPuZ8RtmhGin5Tqmyq5J7XLGiy/E/h\+6r5\+nN08dCW/WW5qQed5yLSTgRuqxRe7Y\+o1db9UJssOyvSknmVvRAtxAIut1cupyKMqlmR/a0PwI2fqt4rP8BkBySHZ9z7RZhtBKmxDFJI83ycvykDZcrF5NeQnO/9S7hFRpamNrz/A/8cNuUX\+5VhnYCDe7\+lvPeeVaWcVDV\+hbSf5L3nRwzthvawygJhzsEDpLC5\+MT/JdI6iS5Ex0nnsMKTRk5OUGmyGW7goH5GzKDTTZFRRhqNmvLyF2qIIHh\ kitchen_docker_key >> /root/.ssh/authorized_keys
